### ISSUE TITLE
Tips/Tutorial

### ISSUE THREAD

**Issue by kamala21** [alexweininger/android-catan#1]
The game is difficult to learn, will there be any tips during game to help the player.  Or a tutorial/guide to help new players to Catan.

**Comment by nirajlmali** [comment]
I agree the game is a bit difficult to learn going in blind. However, the game is extremely expansive and making a tutorial during our timeframe might be more detrimental than useful for us right now.

We'll be sure, however, to have some sort of brief overview and make sure that our activity log for the user. Thanks for the feedback
