### ISSUE TITLE
can't enter the game

### ISSUE THREAD

**Issue by gannotsk21** [alexweininger/android-catan#180]
Can't get past the start game page (where you can name the players).  It doesn't happen all the time but the start game button disappears and then I just need to keep restarting the app till the button appears again.

**Comment by dborg291** [comment]
Please pull the notification bar down and then up again. The bottom bar will disappear.

**Comment by alexweininger** [comment]
@gannotsk21 this is an annoying issue! We are going to try and fix this bug by the next release. I think it is caused by the fullscreen character our game has, which conflicts with a setting in the game framework.

Thanks,

Alex
