### ISSUE TITLE
Crash when trading resources

### ISSUE THREAD

**Issue by kelsicruz** [alexweininger/android-catan#181]
I had no resources to give but tried to get a resource and the game crashed. Doesn't always seem to happen.

**Comment by dborg291** [comment]
If you could provide a more detailed description for the situation that caused the error what'd be awesome.

Thanks!

-db

**Comment by kelsicruz** [comment]
It was my turn, after the settlement phase, and I had zero resources. I tried to do "trade>select resource wanted>confirm" and it crashed for some reason. It didn't do that in subsequent tries to crash it again.

**Comment by alexweininger** [comment]
Thanks @cruzk20!
