### ISSUE TITLE
Intersections and buttons!

### ISSUE THREAD

**Issue by schibel21** [alexweininger/android-catan#184]
When tapping the settlement button, it automatically turns red and tells you to immediately select one intersection but it doesn't do that with any of the other buttons. Also the instructions are unclear on what an intersection is because it will not let me build at an intersection.

**Comment by nirajlmali** [comment]
A few things to make sure:

1. Press menu and make sure have enough resources to build a settlement.
2. Make sure you only have one intersection selected.
3. Intersections are corners of hexagons

We were able to build doing these things so it might be an issue with the instructions. We'll be sure to address this.
