### ISSUE TITLE
Cannot Build Road

### ISSUE THREAD

**Issue by liao21** [alexweininger/android-catan#189]
Played a brick and a wood and clicked the road button. 
Was prompted to "Select two intersections to build a road."
Selected many different combinations for building a road
    settlement, a blank intersection
    end of a road, settlement
    end of road, blank intersection
Could not play any of these roads. Maybe I didn't understand the instructions, but the GUI made it unclear what the issue was.

**Comment by alexweininger** [comment]
Thanks for the input @liao21! We'll look into the issue and get back to you.

**Comment by alexweininger** [comment]
Fixed by changing the intersection and road validation methods. The issue was happening as the selected intersections were inconsistent with what was appearing on screen.
