### ISSUE TITLE
AI Robber

### ISSUE THREAD

**Issue by KawikJaboi** [alexweininger/android-catan#2]
Instead of moving robber to the player with the most victory points, maybe move it to the player who has the best chance of getting resources.

**Comment by nirajlmali** [comment]
I think this is a valid issue to be honest. I'm going to keep it the way it is for now but I think that logic makes more sense and we'll probably implement.

Keeping this issue open to remember this.

**Comment by nirajlmali** [comment]
Made a note of this on our to do list. Thanks for the feedback.
