### ISSUE TITLE
SurfaceView stays black upon starting the game

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/android-catan#211]
When I click 'start' in the game framework I enter the game. The sidebar loads, but the surface view is black and clicking things crashes the app.

I believe this is a loading issue where we are trying to draw the surface view before the game state object is finished making. Hmm...

**Comment by nirajlmali** [comment]
Issue seemed to be with surfaceview being drawn before the gamestate was loaded. Fixed by making sure gamestate and other backend objects were loaded before drawing the surfaceview. GUI is now loading and working perfectly, closing issue.
