### ISSUE TITLE
Inocrrect resources gained

### ISSUE THREAD

**Issue by hthoma20** [alexweininger/android-catan#241]
On the setup phase I should have recieved a brick, wheat, ore (that was my 2nd settlement placement).
My first settlement was on a sheep, sheep, wood.
On the first turn after setup phase, I rolled a five and should have recieved 1 wheat.
My inventory shows that I have 1 brick, 3 wheat, 1 ore, and 1 sheep.

this may be a similar bug to #114

**Comment by alexweininger** [comment]
Thanks I think I know a fix

**Comment by nirajlmali** [comment]
Issue #244 : Issue seemed to be related to the turn logic implementation; issue should be fixed, thank you for feedback.
