### ISSUE TITLE
trade

### ISSUE THREAD

**Issue by hthoma20** [alexweininger/android-catan#242]

**Comment by hthoma20** [comment]
When clicking the trade button, there is no feedback when the trade was failed.

**Comment by hthoma20** [comment]
When i click the trade button, select two resources, and click confirm, nothing happens.
Was the trade processed and failed?
Did it ever go thru?

**Comment by alexweininger** [comment]
We have added more descriptive info messages, and are currently adding a help menu (see #277).

These will help greatly in terms of trading which was pretty confusing to the user.
