### ISSUE TITLE
Moved robber, stole from settlement not adjacent to hexagon

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/android-catan#275]
I moved the hexagon and then I was able to steal from a settlement that was not adjacent to the hex i moved the robber to.

**Comment by nirajlmali** [comment]
Fixed this issue; simply got the current hex of the robber and grabbed all the intersections and looped through the ArrayList to check if any matched the selected intersection ID; if not, we don't allow them to steal from the player who owns the selected building
