### ISSUE TITLE
Help Menu

### ISSUE THREAD

**Issue by dborg291** [alexweininger/android-catan#277]
Game can be confusing to the user.

**Comment by nirajlmali** [comment]
Can this issue be closed? @dborg291

**Comment by nirajlmali** [comment]
Along with the other issues that reference this issue

**Comment by dborg291** [comment]
Help Menu has been fully implemented. From merge #304. Closing this issue (#277) as well as duplicate issues #278 and #281.

**Comment by dborg291** [comment]
Help Menu has been fully implemented. From merge #304. Closing this issue (#277) as well as duplicate issues #278 and #281.
