### ISSUE TITLE
UI not clear on how to clear intersection selections

### ISSUE THREAD

**Issue by nirajlmali** [alexweininger/android-catan#281]
Simply an enhancement but sometimes the user has more than one intersection selected and it may be on accident; the UI isn't very clear on how to clear intersections

This can either be addressed in the help menu or a button can be made that will clear intersections.

**Comment by alexweininger** [comment]
Being fixed along with #277 by @dborg291

**Comment by dborg291** [comment]
The issue was a duplicate of #277. The issue has been addressed, see #277 for more information.
