### ISSUE TITLE
Game crashed with Robber action

### ISSUE THREAD

**Issue by AndrewJLang** [alexweininger/android-catan#296]
Game crashed when pressing confirm button on discard cards menu during robber phase. Proper amount of cards was selected and user had the right cards to get rid of. Error was in CatanHumanPlayer:
![image](https://user-images.githubusercontent.com/43326382/49388636-3a39c200-f6d9-11e8-8bca-67d80b26664f.png)

**Comment by nirajlmali** [comment]
I believe I fixed this issue; there was a bunch of different issues with validation and I think I caught all of them; requires further testing but it should be good to go now
