### ISSUE TITLE
Stuck in discarding phase

### ISSUE THREAD

**Issue by AndrewJLang** [alexweininger/android-catan#297]
"Waiting for other players to discard..." was stuck in a loop. Problem with robber in AI.

**Comment by AndrewJLang** [comment]
Problem dealt was with dumb AI, vital code written in smart AI was not transferred over into dumb AI is more than likely the case.

**Comment by nirajlmali** [comment]
Fixed; some of the logic in how I was adding the resources to the discard list was incorrect; it should be fine now
