### ISSUE TITLE
Typos in Help

### ISSUE THREAD

**Issue by kearneyk-up** [alexweininger/android-catan#306]
There are several typos in the help.
Under "Winning":
- "Each settlement you **upgrad**"
- "once one player places five consecutive roads, they earn a t**or**phy
- "then **there** trophy swi**th**es pla**eyr**s"
- Double space after "additional" on the first line under "Development cards"
- "they are given the largest Ar**mm**y trophy"
- "Public score keeps track of vi**t**ory points from buildings. While private scores keep**s** track of vi**t**ory points from buildings, trophies, and develo**mp**ent cards".
- "Though**t** you cannot your opp**e**nents true" (also, should this be "cannot see"?)
- "Private vi**t**ory points is the only thing that matters"

**Comment by kearneyk-up** [comment]
On "Set-up phase":
- "Set-Up phase is played **i**s Player 1 > Player 2 Player 3 Player 4" is missing '>' between the latter three players.

On "Development cards":
- "Road Bu**ili**ng"
- Year of Plenty - "Use: **TH**e player"

**Comment by kearneyk-up** [comment]
On Trading:
- "Ports can be spe**cail**zed and offer ch**ee**per trading"
- "Ports with a **rs**ource icon on them are spec**ialz**ed"
- "Click on the resource speci**alz**ed resource"
- "Click on the resource you wish to re**x**ieve

On "Robber"
- "any player in the game who has more than **sevenresources**" (missing space between words)
- "The new tile must not be the de**ss**ert tile" (unless it's a particularly sweet tile...)
- "have at least on op**pen**ent".
- After having done so, the player then selects an op**pen**ent.
- Press the Co**nfr**im button"
- "Select an o**pen**ents settlement or city adjacent to the tile"

**Comment by dborg291** [comment]
This is been addressed on a commit awaiting merge.
