### ISSUE TITLE
TESTING

### ISSUE THREAD

**Issue by nirajlmali** [alexweininger/android-catan#313]
The following needs to be tested:

-Getting through a game with:

~1. 4 human players ( 3 network players)~
~2. 1 Human player and all Smart AIs~
~3. 1 Human Player and all Dumb AIS~
~4. 1 of each: Human, Network, Dumb, Smart~

^^^If possible, test more different combinations.

~-Try to win using trophies~
~-Try to win using dev cards~
~-Try to win using both~

~-UNIT TESTS ~

**Comment by dborg291** [comment]
1 Human. 2 Smart AI and 1 Dumb AI: Human won

**Comment by dborg291** [comment]
1 Human, 3 Smart AI: Human won, very close game

**Comment by nirajlmali** [comment]
Human and all Dumb AIs: Human won pretty easily; game is still a bit challenging as dumb AIs will sometimes use robber against the human player so it prevents the human player from having a free win

**Comment by nirajlmali** [comment]
Although Longest Road trophy logic is a bit off, I when I received it along with the Largest Army trophy, I managed to win the game. Built 3 settlement and 2 cities (7 VPs) and got both trophies (4 VPs) giving me a total of 11 VPs. I won after playing a third knight card and gaining the Largest Army Trophy.

**Comment by nirajlmali** [comment]
Main tests have been completed; may do further testing but main tests do work
