### ISSUE TITLE
Help menu odd in some places and nonfunctional in others

### ISSUE THREAD

**Issue by kearneyk-up** [alexweininger/android-catan#315]
The help menu functionality has regressed at some point in the last two days. All but the "development cards" button is non-functional, and the one functional button has z-order issues.
I'm testing with commit 4ef673ed09921aa29e99c95f9c1f27a464ab3c12

Steps to reproduce:
1. Start a game
2. Press "Menu"
3. Click every button except for "development cards".

Expected behavior(1):
A help page appears for each button

Actual behavior (1):
The button changes appearance to indicate that the press has been registered, but nothing happens beyond that.

Steps (continued):
4. Click "development cards"
5. Click "back"

Expected behavior(2):
The "development cards" help shows in the foreground. 
Clicking "back" returns to the help menu.

Actual behavior (2):
The "Development cards" help shows behind the help menu (see screenshot)
![developmentcards](https://user-images.githubusercontent.com/42759124/49565669-cec04200-f8dc-11e8-9923-47d90d151fc4.png)
The "back" button exits the help menu entirely, but leaves the "Building costs" panel in place.
![buildingcosts](https://user-images.githubusercontent.com/42759124/49565728-ff07e080-f8dc-11e8-9d69-a5cf122877eb.png)

Steps (continued):
6. Press "menu"
7. Notice the "building costs" pane vanishes.
8. Press "development cards" twice. 
9. Notice that the second press hides the development cards pane.
10. Press "development cards" a third time.
11. Press "back"
12. Notice that the "building costs" pane is now hidden.
13. Press "menu"
14. Notice that the "building costs" pane appears along with the help, as expected.

Expected vs. actual:
Not applicable here per se. This is just further oddness that I noticed and am documenting in case it helps track down the cause.

**Comment by nirajlmali** [comment]
Hi Dr. Kearney,

We apologize for this bug. We have been doing work on separate branches and this issue has already been addressed. Apologies again. Closing issue.
