### ISSUE TITLE
Smart AI Technique

### ISSUE THREAD

**Issue by Cameron94857** [alexweininger/android-catan#5]
Is there a reason the smart AI always places a development before trading cards? Is there be an advantage in some instances to trade before placing a development (not enough resources)?

**Comment by alexweininger** [comment]
Since there is no cost to playing a dev card, since it has already been built, it can only benefit the player to play the dev card first. Since dev cards can help you gain resources, built, etc.

**Comment by nirajlmali** [comment]
The majority of the development cards either do their job right away (giving resources, adding victory points) or they serve no detrimental value. Monopoly might be the only one that might serve any purpose holding onto. 

Closing issue but thanks for the feedback. If there's time, we may investigate further for holding onto dev. cards but for now, our smart AI will a little more on the aggressive side.
